In [5]:
import pandas as pd
import numpy as np

from datetime import date, datetime
import time 

from sqlalchemy import create_engine, text
import psycopg2

import json
import requests
from bs4 import BeautifulSoup
import re

import matplotlib.pyplot as plt
from catboost import CatBoostRegressor

In [30]:
cats = ['ABS',
 'Trim2',
 'ESC',
 'SteeringLocation',
 'BatteryInfo',
 'DaytimeRunningLight',
 'PedestrianAutomaticEmergencyBraking',
 'TransmissionStyle',
 'WheelBaseType',
 'Trim',
 'ChargerLevel',
 'AutomaticPedestrianAlertingSound',
 'TractionControl',
 'AirBagLocFront',
 'Pretensioner',
 'TransmissionSpeeds',
 'AdaptiveDrivingBeam',
 'Model',
 'BlindSpotMon',
 'EntertainmentSystem',
 'BodyCabType',
 'FuelTypeSecondary',
 'LaneDepartureWarning',
 'TPMS',
 'Seats',
 'FuelInjectionType',
 'EDR',
 'LowerBeamHeadlampLightSource',
 'ParkAssist',
 'AirBagLocCurtain',
 'RearAutomaticEmergencyBraking',
 'RearCrossTrafficAlert',
 'SemiautomaticHeadlampBeamSwitching',
 'CIB',
 'AirBagLocSide',
 'BrakeSystemDesc',
 'KeylessIgnition',
 'EngineConfiguration',
 'AirBagLocKnee',
 'RearVisibilitySystem',
 'VehicleType',
 'AdaptiveCruiseControl',
 'AirBagLocSeatCushion',
 'BlindSpotIntervention',
 'ForwardCollisionWarning',
 'SeatRows',
 'BatteryType',
 'LaneKeepSystem',
 'GVWR',
 'ElectrificationLevel',
 'DynamicBrakeSupport',
 'LaneCenteringAssistance',
 'BedType',
 'BrakeSystemType',
 'Series2',
 'CoolingType',
 'Doors',
 'EngineCylinders',
 'CAN_AACN',
 'Turbo',
 'BodyClass',
 'DriveType',
 'ValveTrainDesign',
 'FuelTypePrimary',
 'Make',
 'AutoReverseSystem',
 'EVDriveUnit',
 'Series',
 'SeatBeltsAll',
 'PlantCity',
 'PlantCountry',
 'PlantState',
 'Note',
 'OtherEngineInfo',
 'GVWR_to',
 'EngineModel',
 'DestinationMarket',
 'ActiveSafetySysNote',
 'state',
 'region',
 'condition',
'paint_color']

nums =  ['ModelYear',
 'WheelSizeRear',
 'BasePrice',
 'WheelSizeFront',
 'CurbWeightLB',
 'WheelBaseShort',
 'WheelBaseLong',
 'BatteryPacks',
 'SAEAutomationLevel',
 'odometer',
 'EngineHP',
 'TopSpeedMPH',
 'TrackWidth',
 'ChargerPowerKW',
 'EngineKW',
 'EngineHP_to',
 'BatteryKWh',
 'BedLengthIN',
 'BatteryV',
 'DisplacementCC',
 'Wheels',
 'Windows',
 'date_posted',
 'state_income']

def model_prep(df2):
    df2[cats] = df2[cats].astype(str)
    df2[nums] = df2[nums].astype('float64')
    return df2

In [7]:
engine = create_engine('postgresql+psycopg2://postgres:p33Gritz!!@localhost:5432/cars')

In [8]:
todays_date = '2024_10_28'

In [15]:
new_link_df = pd.read_sql('new_links_' +todays_date, engine)
new_link_df

,link,price,location,region_url,state,state_income,region
0,https://auburn.craigslist.org/ctd/d/lake-cryst...,57200.0,Lake CRystal Campervan dealer,https://auburn.craigslist.org,al,49671,auburn
1,https://bham.craigslist.org/ctd/d/centreville-...,15900.0,_Nissan_ _NV200 Compact Cargo_ _Van_,https://bham.craigslist.org,al,49671,birmingham
2,https://bham.craigslist.org/ctd/d/centreville-...,35900.0,_Jeep_ _Wrangler Unlimited_ _SUV_,https://bham.craigslist.org,al,49671,birmingham
3,https://bham.craigslist.org/ctd/d/centreville-...,21900.0,_Chevrolet_ _Express Cargo Van_ _Van_,https://bham.craigslist.org,al,49671,birmingham
4,https://bham.craigslist.org/ctd/d/centreville-...,17900.0,_Chevrolet_ _Colorado_ _Truck_,https://bham.craigslist.org,al,49671,birmingham
...,...,...,...,...,...,...,...
33141,https://wyoming.craigslist.org/ctd/d/billings-...,7925.0,"BILLINGS, MT",https://wyoming.craigslist.org,wy,86552,wyoming
33142,https://wyoming.craigslist.org/ctd/d/billings-...,18975.0,"BILLINGS, MT",https://wyoming.craigslist.org,wy,86552,wyoming
33143,https://wyoming.craigslist.org/ctd/d/saint-ste...,31900.0,Peachland,https://wyoming.craigslist.org,wy,86552,wyoming
33144,https://wyoming.craigslist.org/ctd/d/saint-ste...,26500.0,Peachland,https://wyoming.craigslist.org,wy,86552,wyoming
33145,https://wyoming.craigslist.org/ctd/d/lake-crys...,39900.0,Lake Crystal Campervan dealer,https://wyoming.craigslist.org,wy,86552,wyoming

In [14]:
new_listing_df = pd.read_sql('new_listings_' +todays_date, engine)
new_listing_df

,VIN,condition,drive,fuel,odometer,paint_color,title_status,transmission,type,posting_date,lat,long,geo_placename,geo_region,postingbody,title,link
0,3N6CM0KN1LK692922,None,fwd,gas,114374.0,None,clean,automatic,van,2024-10-28 11:31:43,32.967241,-87.166895,Centreville,US-AL,None,2020 Nissan NV200 Compact Cargo for sale - Cen...,https://bham.craigslist.org/ctd/d/centreville-...
1,1C4HJXEG1LW182629,None,4wd,hybrid,58031.0,blue,clean,automatic,SUV,2024-10-28 11:31:38,32.967241,-87.166895,Centreville,US-AL,None,2020 Jeep Wrangler Unlimited hybrid for sale -...,https://bham.craigslist.org/ctd/d/centreville-...
2,1GCWGAFG2K1209883,None,rwd,gas,119024.0,white,clean,automatic,van,2024-10-28 11:31:31,32.967241,-87.166895,Centreville,US-AL,None,2019 Chevrolet Express Cargo Van for sale - Ce...,https://bham.craigslist.org/ctd/d/centreville-...
3,1GCHSCEN8L1148415,None,rwd,gas,108661.0,white,clean,automatic,truck,2024-10-28 11:31:25,32.967241,-87.166895,Centreville,US-AL,None,2020 Chevrolet Colorado for sale - Centreville...,https://bham.craigslist.org/ctd/d/centreville-...
4,3KPF24AD9PE588320,None,fwd,gas,37254.0,None,clean,automatic,sedan,2024-10-28 11:31:19,32.967241,-87.166895,Centreville,US-AL,None,"2023 Kia Forte for sale - Centreville, AL - cr...",https://bham.craigslist.org/ctd/d/centreville-...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3063,1GKKVRED2BJ193120,None,None,gas,134707.0,black,clean,automatic,wagon,2024-10-28 14:18:15,38.741801,-121.290161,Roseville,US-CA,None,"2011 GMC ACADIA for sale - Roseville, CA - cra...",https://sacramento.craigslist.org/ctd/d/rosevi...
3064,1G4GC5ED8BF219315,None,fwd,gas,77000.0,None,clean,automatic,sedan,2024-10-28 14:12:50,38.479700,-121.443800,Sacramento,US-CA,None,"2011 Buick LaCrosse CXL for sale - Sacramento,...",https://sacramento.craigslist.org/ctd/d/sacram...
3065,5J6YH287X8L001024,None,4wd,gas,103653.0,green,clean,automatic,SUV,2024-10-28 14:12:14,38.625271,-121.401879,Sacramento,US-CA,None,"2008 HONDA ELEMENT for sale - Sacramento, CA -...",https://sacramento.craigslist.org/ctd/d/sacram...
3066,2GNAXHEV3M6152264,None,fwd,gas,145000.0,None,clean,automatic,SUV,2024-10-28 14:10:42,38.479700,-121.443800,Sacramento,US-CA,None,2021 Chevrolet Equinox LS FWD for sale - Sacra...,https://sacramento.craigslist.org/ctd/d/sacram...
3067,3GYFNEE38FS522334,None,4wd,gas,144000.0,None,clean,automatic,SUV,2024-10-28 14:08:37,38.479700,-121.443800,Sacramento,US-CA,None,2015 Cadillac SRX Luxury for sale - Sacramento...,https://sacramento.craigslist.org/ctd/d/sacram...

In [19]:
combined_df = pd.merge(new_listing_df, new_link_df, on='link',how='left')

In [20]:
combined_df

,VIN,condition,drive,fuel,odometer,paint_color,title_status,transmission,type,posting_date,...,geo_region,postingbody,title,link,price,location,region_url,state,state_income,region
0,3N6CM0KN1LK692922,None,fwd,gas,114374.0,None,clean,automatic,van,2024-10-28 11:31:43,...,US-AL,None,2020 Nissan NV200 Compact Cargo for sale - Cen...,https://bham.craigslist.org/ctd/d/centreville-...,15900.0,_Nissan_ _NV200 Compact Cargo_ _Van_,https://bham.craigslist.org,al,49671,birmingham
1,1C4HJXEG1LW182629,None,4wd,hybrid,58031.0,blue,clean,automatic,SUV,2024-10-28 11:31:38,...,US-AL,None,2020 Jeep Wrangler Unlimited hybrid for sale -...,https://bham.craigslist.org/ctd/d/centreville-...,35900.0,_Jeep_ _Wrangler Unlimited_ _SUV_,https://bham.craigslist.org,al,49671,birmingham
2,1GCWGAFG2K1209883,None,rwd,gas,119024.0,white,clean,automatic,van,2024-10-28 11:31:31,...,US-AL,None,2019 Chevrolet Express Cargo Van for sale - Ce...,https://bham.craigslist.org/ctd/d/centreville-...,21900.0,_Chevrolet_ _Express Cargo Van_ _Van_,https://bham.craigslist.org,al,49671,birmingham
3,1GCHSCEN8L1148415,None,rwd,gas,108661.0,white,clean,automatic,truck,2024-10-28 11:31:25,...,US-AL,None,2020 Chevrolet Colorado for sale - Centreville...,https://bham.craigslist.org/ctd/d/centreville-...,17900.0,_Chevrolet_ _Colorado_ _Truck_,https://bham.craigslist.org,al,49671,birmingham
4,3KPF24AD9PE588320,None,fwd,gas,37254.0,None,clean,automatic,sedan,2024-10-28 11:31:19,...,US-AL,None,"2023 Kia Forte for sale - Centreville, AL - cr...",https://bham.craigslist.org/ctd/d/centreville-...,18900.0,_Kia_ _Forte_ _Sedan_,https://bham.craigslist.org,al,49671,birmingham
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3063,1GKKVRED2BJ193120,None,None,gas,134707.0,black,clean,automatic,wagon,2024-10-28 14:18:15,...,US-CA,None,"2011 GMC ACADIA for sale - Roseville, CA - cra...",https://sacramento.craigslist.org/ctd/d/rosevi...,7999.0,+ Auto King,https://sacramento.craigslist.org,ca,76800,sacramento
3064,1G4GC5ED8BF219315,None,fwd,gas,77000.0,None,clean,automatic,sedan,2024-10-28 14:12:50,...,US-CA,None,"2011 Buick LaCrosse CXL for sale - Sacramento,...",https://sacramento.craigslist.org/ctd/d/sacram...,9999.0,3463 FLORIN RD,https://sacramento.craigslist.org,ca,76800,sacramento
3065,5J6YH287X8L001024,None,4wd,gas,103653.0,green,clean,automatic,SUV,2024-10-28 14:12:14,...,US-CA,None,"2008 HONDA ELEMENT for sale - Sacramento, CA -...",https://sacramento.craigslist.org/ctd/d/sacram...,14887.0,+ A1 AUTO WHOLESALE,https://sacramento.craigslist.org,ca,76800,sacramento
3066,2GNAXHEV3M6152264,None,fwd,gas,145000.0,None,clean,automatic,SUV,2024-10-28 14:10:42,...,US-CA,None,2021 Chevrolet Equinox LS FWD for sale - Sacra...,https://sacramento.craigslist.org/ctd/d/sacram...,9999.0,3463 FLORIN RD,https://sacramento.craigslist.org,ca,76800,sacramento
3067,3GYFNEE38FS522334,None,4wd,gas,144000.0,None,clean,automatic,SUV,2024-10-28 14:08:37,...,US-CA,None,2015 Cadillac SRX Luxury for sale - Sacramento...,https://sacramento.craigslist.org/ctd/d/sacram...,9999.0,3463 FLORIN RD,https://sacramento.craigslist.org,ca,76800,sacramento

In [ ]:
[x for x in test_stuff.columns.tolist()]

In [33]:
schema = pd.read_sql_query("SELECT column_name, data_type FROM information_schema.columns WHERE table_name='schema_example';", engine)

In [35]:
schema.to_dict()

{'column_name': {0: 'BusLength',
  1: 'AdaptiveHeadlights',
  2: 'Axles',
  3: 'BasePrice',
  4: 'BatteryA',
  5: 'BatteryA_to',
  6: 'BatteryCells',
  7: 'BatteryKWh',
  8: 'BatteryKWh_to',
  9: 'BatteryModules',
  10: 'BatteryPacks',
  11: 'BatteryV',
  12: 'BatteryV_to',
  13: 'BedLengthIN',
  14: 'CashForClunkers',
  15: 'ChargerPowerKW',
  16: 'CurbWeightLB',
  17: 'DisplacementCC',
  18: 'DisplacementCI',
  19: 'DisplacementL',
  20: 'Doors',
  21: 'DriverAssist',
  22: 'EngineCycles',
  23: 'EngineCylinders',
  24: 'EngineHP',
  25: 'EngineHP_to',
  26: 'EngineKW',
  27: 'GCWR',
  28: 'GCWR_to',
  29: 'MakeID',
  30: 'ManufacturerId',
  31: 'ModelID',
  32: 'ModelYear',
  33: 'NCSABodyType',
  34: 'NCSAMake',
  35: 'NCSAMapExcApprovedBy',
  36: 'NCSAMapExcApprovedOn',
  37: 'NCSAMappingException',
  38: 'NCSAModel',
  39: 'NCSANote',
  40: 'NonLandUse',
  41: 'OtherBusInfo',
  42: 'OtherMotorcycleInfo',
  43: 'OtherTrailerInfo',
  44: 'SAEAutomationLevel',
  45: 'SAEAutomationLevel_to',
  46: 'SeatRows',
  47: 'Seats',
  48: 'TopSpeedMPH',
  49: 'TrackWidth',
  50: 'TrailerLength',
  51: 'TransmissionSpeeds',
  52: 'WheelBaseLong',
  53: 'WheelBaseShort',
  54: 'WheelSizeFront',
  55: 'WheelSizeRear',
  56: 'Wheels',
  57: 'Windows',
  58: 'ElectrificationLevel',
  59: 'EngineConfiguration',
  60: 'RearAutomaticEmergencyBraking',
  61: 'RearCrossTrafficAlert',
  62: 'RearVisibilitySystem',
  63: 'Trim',
  64: 'Trim2',
  65: 'EngineManufacturer',
  66: 'EngineModel',
  67: 'EntertainmentSystem',
  68: 'ErrorCode',
  69: 'ErrorText',
  70: 'ForwardCollisionWarning',
  71: 'FuelInjectionType',
  72: 'FuelTypePrimary',
  73: 'FuelTypeSecondary',
  74: 'SeatBeltsAll',
  75: 'Turbo',
  76: 'GVWR',
  77: 'GVWR_to',
  78: 'KeylessIgnition',
  79: 'LaneCenteringAssistance',
  80: 'LaneDepartureWarning',
  81: 'LaneKeepSystem',
  82: 'LowerBeamHeadlampLightSource',
  83: 'Make',
  84: 'VIN',
  85: 'Manufacturer',
  86: 'SemiautomaticHeadlampBeamSwitching',
  87: 'Model',
  88: 'Series',
  89: 'Series2',
  90: 'MotorcycleChassisType',
  91: 'MotorcycleSuspensionType',
  92: 'SteeringLocation',
  93: 'ActiveSafetySysNote',
  94: 'AdaptiveCruiseControl',
  95: 'AdaptiveDrivingBeam',
  96: 'SuggestedVIN',
  97: 'AdditionalErrorText',
  98: 'AirBagLocCurtain',
  99: 'AirBagLocFront',
  100: 'AirBagLocKnee',
  101: 'AirBagLocSeatCushion',
  102: 'AirBagLocSide',
  103: 'AutoReverseSystem',
  104: 'AutomaticPedestrianAlertingSound',
  105: 'AxleConfiguration',
  106: 'TPMS',
  107: 'ValveTrainDesign',
  108: 'VehicleDescriptor',
  109: 'TractionControl',
  110: 'TrailerBodyType',
  111: 'BatteryInfo',
  112: 'VehicleType',
  113: 'Note',
  114: 'TrailerType',
  115: 'OtherEngineInfo',
  116: 'BatteryType',
  117: 'WheelBaseType',
  118: 'OtherRestraintSystemInfo',
  119: 'TransmissionStyle',
  120: 'BedType',
  121: 'BlindSpotIntervention',
  122: 'BlindSpotMon',
  123: 'BodyCabType',
  124: 'BodyClass',
  125: 'BrakeSystemDesc',
  126: 'BrakeSystemType',
  127: 'BusFloorConfigType',
  128: 'ABS',
  129: 'BusType',
  130: 'CAN_AACN',
  131: 'CIB',
  132: 'ParkAssist',
  133: 'ChargerLevel',
  134: 'PedestrianAutomaticEmergencyBraking',
  135: 'CoolingType',
  136: 'PlantCity',
  137: 'CustomMotorcycleType',
  138: 'DaytimeRunningLight',
  139: 'DestinationMarket',
  140: 'PlantCompanyName',
  141: 'PlantCountry',
  142: 'PlantState',
  143: 'PossibleValues',
  144: 'DriveType',
  145: 'Pretensioner',
  146: 'DynamicBrakeSupport',
  147: 'EDR',
  148: 'ESC',
  149: 'EVDriveUnit'},
 'data_type': {0: 'double precision',
  1: 'double precision',
  2: 'double precision',
  3: 'double precision',
  4: 'double precision',
  5: 'double precision',
  6: 'double precision',
  7: 'double precision',
  8: 'double precision',
  9: 'double precision',
  10: 'double precision',
  11: 'double precision',
  12: 'double precision',
  13: 'double precision',
  14: 'double precision',
  15: 'double precision',
  16: 'double precision',
  17: 'double precision',
  18: 'double precision',
  19: 'double precision',
  20: 'double precision',
  21: 'double precision',
  22: 'double precision',
  23: 'double precision',
  24: 'double precision',
  25: 'double precision',
  26: 'double precision',
  27: 'double precision',
  28: 'double precision',
  29: 'double precision',
  30: 'double precision',
  31: 'double precision',
  32: 'double precision',
  33: 'double precision',
  34: 'double precision',
  35: 'double precision',
  36: 'double precision',
  37: 'double precision',
  38: 'double precision',
  39: 'double precision',
  40: 'double precision',
  41: 'double precision',
  42: 'double precision',
  43: 'double precision',
  44: 'double precision',
  45: 'double precision',
  46: 'double precision',
  47: 'double precision',
  48: 'double precision',
  49: 'double precision',
  50: 'double precision',
  51: 'double precision',
  52: 'double precision',
  53: 'double precision',
  54: 'double precision',
  55: 'double precision',
  56: 'double precision',
  57: 'double precision',
  58: 'text',
  59: 'text',
  60: 'text',
  61: 'text',
  62: 'text',
  63: 'text',
  64: 'text',
  65: 'text',
  66: 'text',
  67: 'text',
  68: 'text',
  69: 'text',
  70: 'text',
  71: 'text',
  72: 'text',
  73: 'text',
  74: 'text',
  75: 'text',
  76: 'text',
  77: 'text',
  78: 'text',
  79: 'text',
  80: 'text',
  81: 'text',
  82: 'text',
  83: 'text',
  84: 'text',
  85: 'text',
  86: 'text',
  87: 'text',
  88: 'text',
  89: 'text',
  90: 'text',
  91: 'text',
  92: 'text',
  93: 'text',
  94: 'text',
  95: 'text',
  96: 'text',
  97: 'text',
  98: 'text',
  99: 'text',
  100: 'text',
  101: 'text',
  102: 'text',
  103: 'text',
  104: 'text',
  105: 'text',
  106: 'text',
  107: 'text',
  108: 'text',
  109: 'text',
  110: 'text',
  111: 'text',
  112: 'text',
  113: 'text',
  114: 'text',
  115: 'text',
  116: 'text',
  117: 'text',
  118: 'text',
  119: 'text',
  120: 'text',
  121: 'text',
  122: 'text',
  123: 'text',
  124: 'text',
  125: 'text',
  126: 'text',
  127: 'text',
  128: 'text',
  129: 'text',
  130: 'text',
  131: 'text',
  132: 'text',
  133: 'text',
  134: 'text',
  135: 'text',
  136: 'text',
  137: 'text',
  138: 'text',
  139: 'text',
  140: 'text',
  141: 'text',
  142: 'text',
  143: 'text',
  144: 'text',
  145: 'text',
  146: 'text',
  147: 'text',
  148: 'text',
  149: 'text'}}

In [27]:
test_stuff = pd.read_csv('vin_output_2024_10_21.csv',index_col=[0])
test_stuff.columns.tolist()

['ABS',
 'ActiveSafetySysNote',
 'AdaptiveCruiseControl',
 'AdaptiveDrivingBeam',
 'AdaptiveHeadlights',
 'AdditionalErrorText',
 'AirBagLocCurtain',
 'AirBagLocFront',
 'AirBagLocKnee',
 'AirBagLocSeatCushion',
 'AirBagLocSide',
 'AutoReverseSystem',
 'AutomaticPedestrianAlertingSound',
 'AxleConfiguration',
 'Axles',
 'BasePrice',
 'BatteryA',
 'BatteryA_to',
 'BatteryCells',
 'BatteryInfo',
 'BatteryKWh',
 'BatteryKWh_to',
 'BatteryModules',
 'BatteryPacks',
 'BatteryType',
 'BatteryV',
 'BatteryV_to',
 'BedLengthIN',
 'BedType',
 'BlindSpotIntervention',
 'BlindSpotMon',
 'BodyCabType',
 'BodyClass',
 'BrakeSystemDesc',
 'BrakeSystemType',
 'BusFloorConfigType',
 'BusLength',
 'BusType',
 'CAN_AACN',
 'CIB',
 'CashForClunkers',
 'ChargerLevel',
 'ChargerPowerKW',
 'CoolingType',
 'CurbWeightLB',
 'CustomMotorcycleType',
 'DaytimeRunningLight',
 'DestinationMarket',
 'DisplacementCC',
 'DisplacementCI',
 'DisplacementL',
 'Doors',
 'DriveType',
 'DriverAssist',
 'DynamicBrakeSupport',
 'EDR',
 'ESC',
 'EVDriveUnit',
 'ElectrificationLevel',
 'EngineConfiguration',
 'EngineCycles',
 'EngineCylinders',
 'EngineHP',
 'EngineHP_to',
 'EngineKW',
 'EngineManufacturer',
 'EngineModel',
 'EntertainmentSystem',
 'ErrorCode',
 'ErrorText',
 'ForwardCollisionWarning',
 'FuelInjectionType',
 'FuelTypePrimary',
 'FuelTypeSecondary',
 'GCWR',
 'GCWR_to',
 'GVWR',
 'GVWR_to',
 'KeylessIgnition',
 'LaneCenteringAssistance',
 'LaneDepartureWarning',
 'LaneKeepSystem',
 'LowerBeamHeadlampLightSource',
 'Make',
 'MakeID',
 'Manufacturer',
 'ManufacturerId',
 'Model',
 'ModelID',
 'ModelYear',
 'MotorcycleChassisType',
 'MotorcycleSuspensionType',
 'NCSABodyType',
 'NCSAMake',
 'NCSAMapExcApprovedBy',
 'NCSAMapExcApprovedOn',
 'NCSAMappingException',
 'NCSAModel',
 'NCSANote',
 'NonLandUse',
 'Note',
 'OtherBusInfo',
 'OtherEngineInfo',
 'OtherMotorcycleInfo',
 'OtherRestraintSystemInfo',
 'OtherTrailerInfo',
 'ParkAssist',
 'PedestrianAutomaticEmergencyBraking',
 'PlantCity',
 'PlantCompanyName',
 'PlantCountry',
 'PlantState',
 'PossibleValues',
 'Pretensioner',
 'RearAutomaticEmergencyBraking',
 'RearCrossTrafficAlert',
 'RearVisibilitySystem',
 'SAEAutomationLevel',
 'SAEAutomationLevel_to',
 'SeatBeltsAll',
 'SeatRows',
 'Seats',
 'SemiautomaticHeadlampBeamSwitching',
 'Series',
 'Series2',
 'SteeringLocation',
 'SuggestedVIN',
 'TPMS',
 'TopSpeedMPH',
 'TrackWidth',
 'TractionControl',
 'TrailerBodyType',
 'TrailerLength',
 'TrailerType',
 'TransmissionSpeeds',
 'TransmissionStyle',
 'Trim',
 'Trim2',
 'Turbo',
 'VIN',
 'ValveTrainDesign',
 'VehicleDescriptor',
 'VehicleType',
 'WheelBaseLong',
 'WheelBaseShort',
 'WheelBaseType',
 'WheelSizeFront',
 'WheelSizeRear',
 'Wheels',
 'Windows']

In [44]:
test = test_stuff[test_stuff.VIN.notna()]

In [45]:
test.to_sql('schema_example', con=engine, if_exists='replace',index=False)

32

In [97]:
import pandas as pd
from sqlalchemy import create_engine, text
import requests

def get_json(url):
    try:
        response = requests.get(url)
        response.raise_for_status()
        return response.json()
    except requests.exceptions.HTTPError as http_err:
        print(f"HTTP error occurred: {http_err}")
    except Exception as err:
        print(f"An error occurred: {err}")
    return {}

def vin_decode(vin):
    json_data = get_json(f'https://vpic.nhtsa.dot.gov/api/vehicles/decodevinvalues/{vin}?format=json')
    
    if json_data['Results']:
        df = pd.DataFrame(json_data['Results'])
    else: 
        df = pd.DataFrame(columns=cats + nums)
    return df

def clean_vin_output(df):
    df = df[df['ErrorCode'].isin(['0', '1'])]
    #df = posting_date(df)  # Assuming posting_date is defined elsewhere
    df = df.replace('', 'nan')

    #df[cats] = df[cats].astype(str)
    #df[nums] = df[nums].astype('float64')
    
    df = df.dropna(subset=['Make', 'Model', 'ModelYear', 'VIN'])
    
    value_filter = (df.VehicleType.isin(['TRUCK', 'MULTIPURPOSE PASSENGER VEHICLE (MPV)', 'PASSENGER CAR'])) & (df['BodyClass'].isin(['Pickup',
       'Sport Utility Vehicle (SUV)/Multi-Purpose Vehicle (MPV)',
       'Crossover Utility Vehicle (CUV)', 'Sedan/Saloon',
       'Hatchback/Liftback/Notchback', 'Coupe', 'Convertible/Cabriolet',
       'Minivan', 'Wagon', 'Cargo Van', 'Van']))
       
    df2 = df[value_filter]
    df_bad = df[~value_filter]
    
    return df2, df_bad

def mass_decode(source_table, target_table, reject_table, dbname='cars', user='postgres', password='p33Gritz!!', host='localhost', port='5432'):
    engine = create_engine(f'postgresql+psycopg2://{user}:{password}@{host}:{port}/{dbname}')
    
    try:
        with engine.connect() as conn:
            # Create target and reject tables using schema from schema_example only if they do not exist
            conn.execute(text(f"""
                CREATE TABLE IF NOT EXISTS \"{target_table}\" AS TABLE "schema_example" WITH NO DATA;
            """))
            conn.execute(text(f"""
                CREATE TABLE IF NOT EXISTS \"{reject_table}\" AS TABLE "schema_example" WITH NO DATA;
            """))
            print(f"Ensured that the target table '{target_table}' and reject table '{reject_table}' exist.")

    except Exception as e:
        print(f"Error creating tables: {e}")
        return  # Exit if there's an issue

    # Fetch VINs from source_table
    try:
        with engine.connect() as conn:
            source_vins = pd.read_sql(f'SELECT "VIN" FROM "{source_table}";', conn)
            existing_vins = pd.read_sql(f'SELECT "VIN" FROM "{target_table}";', conn)['VIN'].tolist() if conn.dialect.has_table(conn, target_table) else []
            rejected_vins = pd.read_sql(f'SELECT "VIN" FROM "{reject_table}";', conn)['VIN'].tolist() if conn.dialect.has_table(conn, reject_table) else []
            
        source_vins = source_vins.drop_duplicates(subset=['VIN'])
        
        # Filter VINs that are already processed or rejected
        remaining_vins = source_vins[~source_vins['VIN'].isin(existing_vins + rejected_vins)]
        
        print(f"Found {len(remaining_vins)} remaining VINs to process.")
    
    except Exception as e:
        print(f"Error fetching VINs from tables: {e}")
        return  # Exit if there's an issue

    # Process each remaining VIN
    for _, row in remaining_vins.iterrows():
        vin = row['VIN']
        if pd.isna(vin):  # Skip if VIN is not available
            print(f"Skipping VIN {row['VIN']} due to missing VIN.")
            continue
        
        df = vin_decode(vin)
        
        # Check if we need to overwrite VIN with a new value
        vin2 = df.loc[0, 'VIN'] if not df.empty else None
        if vin2 and vin2 != vin:
            remaining_vins.loc[remaining_vins['VIN'] == vin, 'VIN'] = vin2  # Overwrite the original VIN

        # Clean the output
        valid_df, reject_df = clean_vin_output(df)
        # Insert valid entries into target_table
        if not valid_df.empty:
            valid_df.to_sql(target_table, con=engine, if_exists='append', index=False, method='multi')  # Insert valid entries
            print(f"Inserted {len(valid_df)} valid records for VIN '{vin}' into target table '{target_table}'.")

        # Insert rejected entries into reject_table
        if not reject_df.empty:
            reject_df['VIN'] = vin  # Set the original VIN for rejected entries
            reject_df.to_sql(reject_table, con=engine, if_exists='append', index=False, method='multi')  # Insert rejected entries
            print(f"Inserted {len(reject_df)} rejected records for VIN '{vin}' into reject table '{reject_table}'.")

In [98]:
# Example usage
mass_decode('new_listings_' + todays_date, 'good_vin_' + todays_date, 'bad_vin_' + todays_date)

Ensured that the target table 'good_vin_2024_10_28' and reject table 'bad_vin_2024_10_28' exist.
Found 52 remaining VINs to process.

In [ ]:
df = pd.read_sql('good_vin_2024_10_28', engine)
df = posting_date(df)

backup_data = 'car_data_backup'

df2 = pd.concat([df,backup_data])

df2 = model_prep(df2)

df2 = sql create table 'car_data'

In [49]:
#reference_date = pd.to_datetime('2021-01-01')

def posting_date(df):
    #df['posting_date'] = pd.to_datetime(df['posting_date']).dt.tz_localize(None)
    df['posting_date'] = pd.to_datetime(df['posting_date'], utc=True).dt.tz_localize(None)
    reference_date = pd.to_datetime('2021-01-01')
    df['days_since'] = (df['posting_date'] - reference_date).dt.days
    df['reference_date'] = reference_date
    return df

In [10]:
def get_json(url):
    try:
        response = requests.get(url)
        response.raise_for_status()
        return response.json()
    except requests.exceptions.HTTPError as http_err:
        print(f"HTTP error occurred: {http_err}")
    except Exception as err:
        print(f"An error occurred: {err}")
    return {}

def vin_decode(vin):
    json_data = get_json(f'https://vpic.nhtsa.dot.gov/api/vehicles/decodevinvalues/{vin}?format=json')
    
    if json_data['Results']:
        df = pd.DataFrame(json_data['Results'])
    else: 
        df = pd.DataFrame(columns=cats+nums)
    return df

In [57]:
def clean_vin_output(df):
    df = df[df['ErrorCode'].isin(['0','1'])]
    df = posting_date(df)
    df = df.replace('','nan')

    #df[cats] = df[cats].astype(str)
    #df[nums] = df[nums].astype('float64')
    
    df = df.dropna(subset=['Make','Model','ModelYear','VIN'])
    
    value_filter = (df.VehicleType.isin(['TRUCK', 'MULTIPURPOSE PASSENGER VEHICLE (MPV)', 'PASSENGER CAR'])) & (df['BodyClass'].isin(['Pickup',
       'Sport Utility Vehicle (SUV)/Multi-Purpose Vehicle (MPV)',
       'Crossover Utility Vehicle (CUV)', 'Sedan/Saloon',
       'Hatchback/Liftback/Notchback', 'Coupe', 'Convertible/Cabriolet',
       'Minivan', 'Wagon', 'Cargo Van', 'Van']))
       
    df2 = df[value_filter]
    df_bad = df[~value_filter]
    
    return df2, df_bad

In [3]:
df2 = pd.read_csv('no_repeats_fixed_cylinders.csv', index_col=[0], dtype={'EngineCylinders': str})

C:\Users\mitch\AppData\Local\Temp\ipykernel_16992\2353025374.py:1: DtypeWarning: Columns (9,33,45,59,61,72,83,86,116,118,119,130,154,157,158,160,162,165,168,169,177,178,179) have mixed types. Specify dtype option on import or set low_memory=False.
  df2 = pd.read_csv('no_repeats_fixed_cylinders.csv', index_col=[0], dtype={'EngineCylinders': str})

In [4]:

import pandas as pd
#df = pd.read_csv('car_data_latest.csv', index_col=[0], dtype={'EngineCylinders': str})

df[df.VIN == '3C7WRMDL7MG517473']

Empty DataFrame
Columns: [VIN, odometer, price, ABS, ActiveSafetySysNote, AdaptiveCruiseControl, AdaptiveDrivingBeam, AdaptiveHeadlights, AdditionalErrorText, AirBagLocCurtain, AirBagLocFront, AirBagLocKnee, AirBagLocSeatCushion, AirBagLocSide, AutoReverseSystem, AutomaticPedestrianAlertingSound, AxleConfiguration, Axles, BasePrice, BatteryA, BatteryA_to, BatteryCells, BatteryInfo, BatteryKWh, BatteryKWh_to, BatteryModules, BatteryPacks, BatteryType, BatteryV, BatteryV_to, BedLengthIN, BedType, BlindSpotIntervention, BlindSpotMon, BodyCabType, BodyClass, BrakeSystemDesc, BrakeSystemType, BusFloorConfigType, BusLength, BusType, CAN_AACN, CIB, CashForClunkers, ChargerLevel, ChargerPowerKW, CoolingType, CurbWeightLB, CustomMotorcycleType, DaytimeRunningLight, DestinationMarket, DisplacementCC, DisplacementCI, DisplacementL, Doors, DriveType, DriverAssist, DynamicBrakeSupport, EDR, ESC, EVDriveUnit, ElectrificationLevel, EngineConfiguration, EngineCycles, EngineCylinders, EngineHP, EngineHP_to, EngineKW, EngineManufacturer, EngineModel, EntertainmentSystem, ErrorCode, ErrorText, ForwardCollisionWarning, FuelInjectionType, FuelTypePrimary, FuelTypeSecondary, GCWR, GCWR_to, GVWR, GVWR_to, KeylessIgnition, LaneCenteringAssistance, LaneDepartureWarning, LaneKeepSystem, LowerBeamHeadlampLightSource, Make, MakeID, Manufacturer, ManufacturerId, Model, ModelID, ModelYear, MotorcycleChassisType, MotorcycleSuspensionType, NCSABodyType, NCSAMake, NCSAMapExcApprovedBy, NCSAMapExcApprovedOn, NCSAMappingException, ...]
Index: []

[0 rows x 175 columns]

In [16]:
df2[['Make','id']]

            Make            id
0            GMC  7.316815e+09
1      CHEVROLET  7.316815e+09
2            GMC  7.316343e+09
3         TOYOTA  7.315276e+09
4            GMC  7.313388e+09
...          ...           ...
82798       FORD           NaN
82799     TOYOTA           NaN
82800       FORD           NaN
82801     TOYOTA           NaN
82802        RAM           NaN

[76551 rows x 2 columns]

In [8]:
df2.loc[df2.link.isnull(), 'link'] = df2['url']

In [4]:
df2.columns.tolist()

['VIN',
 'odometer',
 'price',
 'ABS',
 'ActiveSafetySysNote',
 'AdaptiveCruiseControl',
 'AdaptiveDrivingBeam',
 'AdaptiveHeadlights',
 'AdditionalErrorText',
 'AirBagLocCurtain',
 'AirBagLocFront',
 'AirBagLocKnee',
 'AirBagLocSeatCushion',
 'AirBagLocSide',
 'AutoReverseSystem',
 'AutomaticPedestrianAlertingSound',
 'AxleConfiguration',
 'Axles',
 'BasePrice',
 'BatteryA',
 'BatteryA_to',
 'BatteryCells',
 'BatteryInfo',
 'BatteryKWh',
 'BatteryKWh_to',
 'BatteryModules',
 'BatteryPacks',
 'BatteryType',
 'BatteryV',
 'BatteryV_to',
 'BedLengthIN',
 'BedType',
 'BlindSpotIntervention',
 'BlindSpotMon',
 'BodyCabType',
 'BodyClass',
 'BrakeSystemDesc',
 'BrakeSystemType',
 'BusFloorConfigType',
 'BusLength',
 'BusType',
 'CAN_AACN',
 'CIB',
 'CashForClunkers',
 'ChargerLevel',
 'ChargerPowerKW',
 'CoolingType',
 'CurbWeightLB',
 'CustomMotorcycleType',
 'DaytimeRunningLight',
 'DestinationMarket',
 'DisplacementCC',
 'DisplacementCI',
 'DisplacementL',
 'Doors',
 'DriveType',
 'DriverAssist',
 'DynamicBrakeSupport',
 'EDR',
 'ESC',
 'EVDriveUnit',
 'ElectrificationLevel',
 'EngineConfiguration',
 'EngineCycles',
 'EngineCylinders',
 'EngineHP',
 'EngineHP_to',
 'EngineKW',
 'EngineManufacturer',
 'EngineModel',
 'EntertainmentSystem',
 'ErrorCode',
 'ErrorText',
 'ForwardCollisionWarning',
 'FuelInjectionType',
 'FuelTypePrimary',
 'FuelTypeSecondary',
 'GCWR',
 'GCWR_to',
 'GVWR',
 'GVWR_to',
 'KeylessIgnition',
 'LaneCenteringAssistance',
 'LaneDepartureWarning',
 'LaneKeepSystem',
 'LowerBeamHeadlampLightSource',
 'Make',
 'MakeID',
 'Manufacturer',
 'ManufacturerId',
 'Model',
 'ModelID',
 'ModelYear',
 'MotorcycleChassisType',
 'MotorcycleSuspensionType',
 'NCSABodyType',
 'NCSAMake',
 'NCSAMapExcApprovedBy',
 'NCSAMapExcApprovedOn',
 'NCSAMappingException',
 'NCSAModel',
 'NCSANote',
 'NonLandUse',
 'Note',
 'OtherBusInfo',
 'OtherEngineInfo',
 'OtherMotorcycleInfo',
 'OtherRestraintSystemInfo',
 'OtherTrailerInfo',
 'ParkAssist',
 'PedestrianAutomaticEmergencyBraking',
 'PlantCity',
 'PlantCompanyName',
 'PlantCountry',
 'PlantState',
 'PossibleValues',
 'Pretensioner',
 'RearAutomaticEmergencyBraking',
 'RearCrossTrafficAlert',
 'RearVisibilitySystem',
 'SAEAutomationLevel',
 'SAEAutomationLevel_to',
 'SeatBeltsAll',
 'SeatRows',
 'Seats',
 'SemiautomaticHeadlampBeamSwitching',
 'Series',
 'Series2',
 'SteeringLocation',
 'SuggestedVIN',
 'TPMS',
 'TopSpeedMPH',
 'TrackWidth',
 'TractionControl',
 'TrailerBodyType',
 'TrailerLength',
 'TrailerType',
 'TransmissionSpeeds',
 'TransmissionStyle',
 'Trim',
 'Trim2',
 'Turbo',
 'ValveTrainDesign',
 'VehicleDescriptor',
 'VehicleType',
 'WheelBaseLong',
 'WheelBaseShort',
 'WheelBaseType',
 'WheelSizeFront',
 'WheelSizeRear',
 'Wheels',
 'Windows',
 'id',
 'url',
 'region_url',
 'year',
 'manufacturer',
 'model',
 'condition',
 'cylinders',
 'fuel',
 'title_status',
 'transmission',
 'drive',
 'size',
 'type',
 'paint_color',
 'image_url',
 'description',
 'county',
 'lat',
 'long',
 'posting_date',
 'Year',
 'displ',
 'date_posted',
 'link',
 'location',
 'title',
 'Message',
 'y_pred',
 'error',
 'abs_error',
 'state',
 'region',
 'state_income',
 'pred']

In [43]:
sql_cols = [x for x in df2.columns.tolist() if x not in ['Message','location','displ','Year','description','image_url','url', 'id']]

In [44]:
df2[sql_cols]

,VIN,odometer,price,ABS,ActiveSafetySysNote,AdaptiveCruiseControl,AdaptiveDrivingBeam,AdaptiveHeadlights,AdditionalErrorText,AirBagLocCurtain,...,date_posted,link,title,y_pred,error,abs_error,state,region,state_income,pred
0,3GTP1VEC4EG551563,57923.0,33590.0,nan,nan,nan,nan,NaN,NaN,All Rows,...,-972.0,https://auburn.craigslist.org/ctd/d/auburn-uni...,NaN,32200.656024,-888.432082,1389.343976,al,auburn,49671.0,32701.567918
1,1GCSCSE06AZ123805,71229.0,22590.0,nan,nan,nan,nan,NaN,NaN,nan,...,-972.0,https://auburn.craigslist.org/ctd/d/auburn-uni...,NaN,20866.998271,-2738.510378,1723.001729,al,auburn,49671.0,19851.489622
2,1GT220CG8CZ231238,68696.0,27990.0,nan,nan,nan,nan,NaN,NaN,nan,...,-973.0,https://auburn.craigslist.org/ctd/d/auburn-uni...,NaN,30457.180476,1254.378745,2467.180476,al,auburn,49671.0,29244.378745
3,5TFEY5F15EX169621,55251.0,33590.0,nan,nan,nan,nan,NaN,NaN,All Rows,...,-975.0,https://auburn.craigslist.org/ctd/d/auburn-uni...,NaN,31725.710214,956.509526,1864.289786,al,auburn,49671.0,34546.509526
4,1GTR1WE07DZ143724,80318.0,24590.0,nan,nan,nan,nan,NaN,NaN,All Rows,...,-979.0,https://auburn.craigslist.org/ctd/d/auburn-uni...,NaN,23642.238391,-980.687696,947.761609,al,auburn,49671.0,23609.312304
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82798,3FMCR9B62MRA71761,75864.0,21950.0,nan,nan,nan,nan,NaN,NaN,nan,...,-92.0,https://denver.craigslist.org/ctd/d/englewood-...,"2021 FORD BRONCO SPORT for sale - Englewood, C...",23740.996597,2165.613043,1790.996597,co,denver,70715.0,24115.613043
82799,3TMMU4FN8FM077138,174169.0,18900.0,nan,nan,nan,nan,NaN,NaN,All Rows,...,-92.0,https://denver.craigslist.org/ctd/d/denver-201...,"2015 Toyota Tacoma V6 for sale - Denver, CO - ...",22074.596765,1544.364071,3174.596765,co,denver,70715.0,20444.364071
82800,1FT7W2BT5KED42260,124785.0,41999.0,Standard,nan,nan,nan,NaN,NaN,nan,...,-92.0,https://denver.craigslist.org/ctd/d/longmont-2...,2019 Ford F-250 Super Duty Lariat diesel for s...,42687.208603,927.427216,688.208603,co,denver,70715.0,42926.427216
82801,4T3D6RFV8MU055692,103290.0,26500.0,Standard,nan,Standard,nan,NaN,NaN,All Rows,...,-92.0,https://denver.craigslist.org/ctd/d/denver-202...,"2021 TOYOTA RAV4 hybrid for sale - Denver, CO ...",28185.686543,1098.024199,1685.686543,co,denver,70715.0,27598.024199
82802,1C6RR7TT9ES470655,156565.0,14900.0,nan,nan,nan,nan,NaN,NaN,nan,...,-92.0,https://denver.craigslist.org/ctd/d/denver-201...,"2014 Ram 1500 Big Horn for sale - Denver, CO -...",15203.010783,1918.176525,303.010783,co,denver,70715.0,16818.176525

In [45]:
cats = ['ABS',
 'Trim2',
 'ESC',
 'SteeringLocation',
 'BatteryInfo',
 'DaytimeRunningLight',
 'PedestrianAutomaticEmergencyBraking',
 'TransmissionStyle',
 'WheelBaseType',
 'Trim',
 'ChargerLevel',
 'AutomaticPedestrianAlertingSound',
 'TractionControl',
 'AirBagLocFront',
 'Pretensioner',
 'TransmissionSpeeds',
 'AdaptiveDrivingBeam',
 'Model',
 'BlindSpotMon',
 'EntertainmentSystem',
 'BodyCabType',
 'FuelTypeSecondary',
 'LaneDepartureWarning',
 'TPMS',
 'Seats',
 'FuelInjectionType',
 'EDR',
 'LowerBeamHeadlampLightSource',
 'ParkAssist',
 'AirBagLocCurtain',
 'RearAutomaticEmergencyBraking',
 'RearCrossTrafficAlert',
 'SemiautomaticHeadlampBeamSwitching',
 'CIB',
 'AirBagLocSide',
 'BrakeSystemDesc',
 'KeylessIgnition',
 'EngineConfiguration',
 'AirBagLocKnee',
 'RearVisibilitySystem',
 'VehicleType',
 'AdaptiveCruiseControl',
 'AirBagLocSeatCushion',
 'BlindSpotIntervention',
 'ForwardCollisionWarning',
 'SeatRows',
 'BatteryType',
 'LaneKeepSystem',
 'GVWR',
 'ElectrificationLevel',
 'DynamicBrakeSupport',
 'LaneCenteringAssistance',
 'BedType',
 'BrakeSystemType',
 'Series2',
 'CoolingType',
 'Doors',
 'EngineCylinders',
 'CAN_AACN',
 'Turbo',
 'BodyClass',
 'DriveType',
 'ValveTrainDesign',
 'FuelTypePrimary',
 'Make',
 'AutoReverseSystem',
 'EVDriveUnit',
 'Series',
 'SeatBeltsAll',
 'PlantCity',
 'PlantCountry',
 'PlantState',
 'Note',
 'OtherEngineInfo',
 'GVWR_to',
 'EngineModel',
 'DestinationMarket',
 'ActiveSafetySysNote',
 'state',
 'region',
 'condition',
'paint_color']

nums =  ['ModelYear',
 'WheelSizeRear',
 'BasePrice',
 'WheelSizeFront',
 'CurbWeightLB',
 'WheelBaseShort',
 'WheelBaseLong',
 'BatteryPacks',
 'SAEAutomationLevel',
 'odometer',
 'EngineHP',
 'TopSpeedMPH',
 'TrackWidth',
 'ChargerPowerKW',
 'EngineKW',
 'EngineHP_to',
 'BatteryKWh',
 'BedLengthIN',
 'BatteryV',
 'DisplacementCC',
 'Wheels',
 'Windows',
 'date_posted',
 'state_income']

def model_prep(df2):
    df2[cats] = df2[cats].astype(str)
    df2[nums] = df2[nums].astype('float64')
    return df2

df2 = model_prep(df2)

In [88]:
import psycopg2

conn = psycopg2.connect(
    host="localhost",
    port=5432, # your server hostname
    database="cars",     # your database name
    user="postgres",   # your database username
    password="p33Gritz!!" # your database password
)

In [89]:
cur = conn.cursor()

In [49]:
def map_dtype(dtype):
    if pd.api.types.is_integer_dtype(dtype):
        return "INTEGER"
    elif pd.api.types.is_float_dtype(dtype):
        return "REAL"
    elif pd.api.types.is_numeric_dtype(dtype):
        return "NUMERIC"
    elif pd.api.types.is_string_dtype(dtype):
        return "VARCHAR"
    else:
        return "TEXT"

In [48]:
columns = ", ".join([f"{col} {map_dtype(dtype)}" for col, dtype in df2[sql_cols].dtypes.items()])
columns

'VIN VARCHAR, odometer REAL, price REAL, ABS VARCHAR, ActiveSafetySysNote VARCHAR, AdaptiveCruiseControl VARCHAR, AdaptiveDrivingBeam VARCHAR, AdaptiveHeadlights REAL, AdditionalErrorText VARCHAR, AirBagLocCurtain VARCHAR, AirBagLocFront VARCHAR, AirBagLocKnee VARCHAR, AirBagLocSeatCushion VARCHAR, AirBagLocSide VARCHAR, AutoReverseSystem VARCHAR, AutomaticPedestrianAlertingSound VARCHAR, AxleConfiguration REAL, Axles REAL, BasePrice REAL, BatteryA REAL, BatteryA_to REAL, BatteryCells REAL, BatteryInfo VARCHAR, BatteryKWh REAL, BatteryKWh_to REAL, BatteryModules REAL, BatteryPacks REAL, BatteryType VARCHAR, BatteryV REAL, BatteryV_to REAL, BedLengthIN REAL, BedType VARCHAR, BlindSpotIntervention VARCHAR, BlindSpotMon VARCHAR, BodyCabType VARCHAR, BodyClass VARCHAR, BrakeSystemDesc VARCHAR, BrakeSystemType VARCHAR, BusFloorConfigType VARCHAR, BusLength REAL, BusType VARCHAR, CAN_AACN VARCHAR, CIB VARCHAR, CashForClunkers REAL, ChargerLevel VARCHAR, ChargerPowerKW REAL, CoolingType VARCHAR, CurbWeightLB REAL, CustomMotorcycleType VARCHAR, DaytimeRunningLight VARCHAR, DestinationMarket VARCHAR, DisplacementCC REAL, DisplacementCI REAL, DisplacementL REAL, Doors VARCHAR, DriveType VARCHAR, DriverAssist REAL, DynamicBrakeSupport VARCHAR, EDR VARCHAR, ESC VARCHAR, EVDriveUnit VARCHAR, ElectrificationLevel VARCHAR, EngineConfiguration VARCHAR, EngineCycles REAL, EngineCylinders VARCHAR, EngineHP REAL, EngineHP_to REAL, EngineKW REAL, EngineManufacturer VARCHAR, EngineModel VARCHAR, EntertainmentSystem VARCHAR, ErrorCode VARCHAR, ErrorText VARCHAR, ForwardCollisionWarning VARCHAR, FuelInjectionType VARCHAR, FuelTypePrimary VARCHAR, FuelTypeSecondary VARCHAR, GCWR REAL, GCWR_to REAL, GVWR VARCHAR, GVWR_to VARCHAR, KeylessIgnition VARCHAR, LaneCenteringAssistance VARCHAR, LaneDepartureWarning VARCHAR, LaneKeepSystem VARCHAR, LowerBeamHeadlampLightSource VARCHAR, Make VARCHAR, MakeID REAL, Manufacturer VARCHAR, ManufacturerId REAL, Model VARCHAR, ModelID REAL, ModelYear REAL, MotorcycleChassisType VARCHAR, MotorcycleSuspensionType VARCHAR, NCSABodyType REAL, NCSAMake REAL, NCSAMapExcApprovedBy REAL, NCSAMapExcApprovedOn REAL, NCSAMappingException REAL, NCSAModel REAL, NCSANote REAL, NonLandUse REAL, Note VARCHAR, OtherBusInfo REAL, OtherEngineInfo VARCHAR, OtherMotorcycleInfo REAL, OtherRestraintSystemInfo VARCHAR, OtherTrailerInfo REAL, ParkAssist VARCHAR, PedestrianAutomaticEmergencyBraking VARCHAR, PlantCity VARCHAR, PlantCompanyName VARCHAR, PlantCountry VARCHAR, PlantState VARCHAR, PossibleValues VARCHAR, Pretensioner VARCHAR, RearAutomaticEmergencyBraking VARCHAR, RearCrossTrafficAlert VARCHAR, RearVisibilitySystem VARCHAR, SAEAutomationLevel REAL, SAEAutomationLevel_to REAL, SeatBeltsAll VARCHAR, SeatRows VARCHAR, Seats VARCHAR, SemiautomaticHeadlampBeamSwitching VARCHAR, Series VARCHAR, Series2 VARCHAR, SteeringLocation VARCHAR, SuggestedVIN VARCHAR, TPMS VARCHAR, TopSpeedMPH REAL, TrackWidth REAL, TractionControl VARCHAR, TrailerBodyType VARCHAR, TrailerLength REAL, TrailerType VARCHAR, TransmissionSpeeds VARCHAR, TransmissionStyle VARCHAR, Trim VARCHAR, Trim2 VARCHAR, Turbo VARCHAR, ValveTrainDesign VARCHAR, VehicleDescriptor VARCHAR, VehicleType VARCHAR, WheelBaseLong REAL, WheelBaseShort REAL, WheelBaseType VARCHAR, WheelSizeFront REAL, WheelSizeRear REAL, Wheels REAL, Windows REAL, region_url VARCHAR, year REAL, cl_make VARCHAR, cl_model VARCHAR, condition VARCHAR, cylinders VARCHAR, fuel VARCHAR, title_status VARCHAR, transmission VARCHAR, drive VARCHAR, size VARCHAR, type VARCHAR, paint_color VARCHAR, county REAL, lat REAL, long REAL, posting_date VARCHAR, date_posted REAL, link VARCHAR, title VARCHAR, y_pred REAL, error REAL, abs_error REAL, state VARCHAR, region VARCHAR, state_income REAL, pred REAL'

In [42]:
[x for x in df2.columns if 'manu' in x]

[]

In [40]:
df2 = df2.rename(columns={'manufacturer' : 'cl_make','model' : 'cl_model'})

In [52]:
table_name = "car_data"
create_table_query = f"CREATE TABLE IF NOT EXISTS {table_name} (id SERIAL PRIMARY KEY, {columns});"
cur.execute(create_table_query)

In [53]:
conn.commit()

In [54]:
for index, row in df2.iterrows():
    # Filter the row to only include the specified columns
    filtered_row = row[sql_cols]

    cur.execute(
        f"INSERT INTO {table_name} ({', '.join(sql_cols)}) VALUES ({', '.join(['%s'] * len(filtered_row))})",
        tuple(filtered_row)
    )

# Commit the transaction
conn.commit()

# Close the cursor and connection
cur.close()
conn.close()

In [55]:
#df2[sql_cols].to_csv('car_data_sql.csv')

In [58]:
reg_ref = pd.read_csv('reg_ref_df.csv',index_col=[0])
reg_ref

,state,state_income,region,region_url
0,al,49671,auburn,https://auburn.craigslist.org
106,al,49671,birmingham,https://bham.craigslist.org
620,al,49671,dothan,https://dothan.craigslist.org
677,al,49671,florence / muscle shoals,https://shoals.craigslist.org
729,al,49671,gadsden-anniston,https://gadsden.craigslist.org
...,...,...,...,...
85597,wi,59787,madison,https://madison.craigslist.org
86571,wi,59787,northern WI,https://northernwi.craigslist.org
86589,wi,59787,sheboygan,https://sheboygan.craigslist.org
86677,wi,59787,wausau,https://wausau.craigslist.org
86811,wy,86552,wyoming,https://wyoming.craigslist.org

In [59]:
columns1 = ", ".join([f"{col} {map_dtype(dtype)}" for col, dtype in reg_ref.dtypes.items()])
columns1

'state VARCHAR, state_income INTEGER, region VARCHAR, region_url VARCHAR'

In [60]:
table_name = "car_data"
create_table_query = f"CREATE TABLE IF NOT EXISTS {table_name} (id SERIAL PRIMARY KEY, {columns});"
cur.execute(create_table_query)

In [61]:
conn.commit()

In [67]:
for index, row in reg_ref.iterrows():
    cur.execute(
        f"INSERT INTO {table_name1} ({', '.join(reg_ref.columns)}) VALUES ({', '.join(['%s'] * len(row))})",
        tuple(row)
    )

# Commit the transaction
conn.commit()

# Close the cursor and connection
cur.close()
conn.close()

In [68]:
from datetime import date

'listing_scrape_res_' + date.today().strftime('%Y-%m-%d') + '.csv'

'listing_scrape_res_2024-10-21.csv'

In [79]:
import psycopg2

conn = psycopg2.connect(
    host="localhost",
    port=5432, # your server hostname
    database="cars",     # your database name
    user="postgres",   # your database username
    password="p33Gritz!!" # your database password
)

def create_table_df(df, table_name, cols=None):
    # Use all columns if none are specified
    if cols is None:
        cols = df.columns.tolist()  # Convert Index to list

    # Ensure the specified columns are valid
    cols = [col for col in cols if col in df.columns]

    # Generate column definitions for SQL
    columns1 = ", ".join([f"{col} {map_dtype(dtype)}" for col, dtype in df[cols].dtypes.items()])
    create_table_query1 = f"CREATE TABLE IF NOT EXISTS {table_name} (id SERIAL PRIMARY KEY, {columns1});"
    
    # Execute the create table query
    cur.execute(create_table_query1)
    conn.commit()
    
    # Insert data into the table
    for index, row in df[cols].iterrows():  # Use only the specified columns for inserting
        cur.execute(
            f"INSERT INTO {table_name} ({', '.join(cols)}) VALUES ({', '.join(['%s'] * len(row))})",
            tuple(row)
        )

    # Commit the transaction
    conn.commit()

In [81]:
cur = conn.cursor()

create_table_df(need_plus_region, 'new_links_'+ date.today().strftime('%Y_%m_%d'))

# Close the cursor and connection
#cur.close()
#conn.close()

# Above: Initial sql table populating: car_data, region_ref, links

# Read csv -> read sql: table_name and df_name needed. 'id' col created

In [98]:
tb_name = 'new_links_'+ try:
    # Step 1: Create the backup table name with the current date
    backup_table_name = 'car_data_' + date.today().strftime('%Y_%m_%d') + '_backup'

    # Step 2: Rename car_data_latest to the new backup table name
    cur.execute(f"""
        ALTER TABLE car_data_latest RENAME TO {backup_table_name};
    """)

    # Step 3: Create new car_data_latest table by merging new_listings and car_data_backup
    # You can adjust the columns as necessary to match your requirements
    cur.execute("""
        CREATE TABLE car_data_latest AS
        SELECT *
        FROM new_listings
        UNION ALL
        SELECT *
        FROM {};
    """.format(backup_table_name))  # Use the new backup table name

    # Commit the transaction
    conn.commit()

    print(f"Tables merged successfully. '{backup_table_name}' created, and 'car_data_latest' renamed to '{backup_table_name}'.")

except Exception as e:
    print(f"An error occurred: {e}")
    conn.rollback()  # Roll back the transaction in case of error

finally:
    # Close the cursor and connection
    cur.close()
    conn.close()

cur = conn.cursor()
query = "SELECT * FROM " + tb_name + ";" 

latest_links_df = pd.read_sql(query, conn)

C:\Users\mitch\AppData\Local\Temp\ipykernel_16992\3079492494.py:11: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  latest_links_df = pd.read_sql(query, conn)

# Creating reg_ref_df from sql table 'region_reference'

In [103]:
tb_name = 'region_reference'

cur = conn.cursor()
query = "SELECT * FROM " + tb_name + ";" 

reg_ref_df = pd.read_sql(query, conn)
reg_ref_df

C:\Users\mitch\AppData\Local\Temp\ipykernel_16992\349600406.py:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  reg_ref_df = pd.read_sql(query, conn)

,id,state,state_income,region,region_url
0,1,al,49671,auburn,https://auburn.craigslist.org
1,2,al,49671,birmingham,https://bham.craigslist.org
2,3,al,49671,dothan,https://dothan.craigslist.org
3,4,al,49671,florence / muscle shoals,https://shoals.craigslist.org
4,5,al,49671,gadsden-anniston,https://gadsden.craigslist.org
...,...,...,...,...,...
404,405,wi,59787,madison,https://madison.craigslist.org
405,406,wi,59787,northern WI,https://northernwi.craigslist.org
406,407,wi,59787,sheboygan,https://sheboygan.craigslist.org
407,408,wi,59787,wausau,https://wausau.craigslist.org
408,409,wy,86552,wyoming,https://wyoming.craigslist.org

# Step 4: merge vin_output / cleaned data with 'car_data_latest'

In [ ]:
# Save backup

In [ ]:
try:
    # Step 1: Rename car_data_latest to car_data_backup
    cur.execute("""
        ALTER TABLE car_data_latest RENAME TO car_data_backup;
    """)
    
    # Step 2: Create new car_data_latest table by merging new_listings and car_data_backup
    # You can adjust the columns as necessary to match your requirements
    cur.execute("""
        CREATE TABLE car_data_latest AS
        SELECT *
        FROM new_listings
        UNION ALL
        SELECT *
        FROM car_data_backup;
    """)
    
    # Commit the transaction
    conn.commit()

    print("Tables merged successfully. 'car_data_latest' created, and 'car_data_latest' renamed to 'car_data_backup'.")

except Exception as e:
    print(f"An error occurred: {e}")
    conn.rollback()  # Roll back the transaction in case of error

finally:
    # Close the cursor and connection
    cur.close()
    conn.close()